# Generated by Django 3.1 on 2020-09-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=15)),
                ('long', models.CharField(max_length=15)),
                ('status_driver', models.BooleanField(default=False)),
                ('name_point', models.CharField(max_length=10)),
            ],
        ),
    ]
