# Generated by Django 3.1 on 2020-08-27 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20200825_2358'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.AddField(
            model_name='student',
            name='user_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
