# Generated by Django 3.0.7 on 2020-06-27 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Onibus', models.CharField(max_length=20)),
                ('pontos', models.CharField(max_length=200)),
                ('passou_no_ponto', models.BooleanField(default=False)),
                ('motorista_usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_responsavel', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('ponto', models.CharField(max_length=500)),
                ('matricula', models.CharField(max_length=40)),
                ('aluno_usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
