# Generated by Django 3.0.7 on 2020-06-30 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bus_system_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorista',
            old_name='Onibus',
            new_name='onibus',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='motorista_usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
