# Generated by Django 3.0.7 on 2020-06-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_system_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone_responsavel',
            field=models.IntegerField(),
        ),
    ]
